"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Zone={province:string;district:string;locality:string|null};
type User={id:number;username:string;name:string;role:string;active:boolean;lastLoginAt:string|null;zones:Zone[]};
export default function UsuariosPage(){
 const router=useRouter(); const [users,setUsers]=useState<User[]>([]); const [error,setError]=useState("");
 const [form,setForm]=useState({username:"",name:"",password:"",role:"OPERATOR",province:"Buenos Aires",district:"",locality:""});
 async function load(){const me=await fetch('/api/admin/me',{cache:'no-store'}); if(!me.ok){router.push('/admin/login');return} const md=await me.json(); if(md.user?.role!=="ADMIN"){router.push('/admin');return} const r=await fetch('/api/admin/users',{cache:'no-store'}); const d=await r.json(); if(d.success)setUsers(d.users);}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setError("");const zones=form.district?[{province:form.province,district:form.district,locality:form.locality||null}]:[];const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,zones})});const d=await r.json();if(!d.success){setError(d.error||'Error');return}setForm({...form,username:"",name:"",password:"",district:"",locality:""});load();}
 async function toggle(u:User){await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:u.id,active:!u.active})});load();}
 return <main className="min-h-screen bg-slate-950 p-4 text-white sm:p-8"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-red-400">Administración</p><h1 className="text-3xl font-black">Usuarios del Centro</h1></div><div className="flex gap-2"><a href="/admin/auditoria" className="rounded-xl border border-slate-700 px-4 py-2">📋 Auditoría</a><button onClick={()=>router.push('/admin')} className="rounded-xl border border-slate-700 px-4 py-2">← Monitoreo</button></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={create} className="rounded-3xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-black">Crear usuario</h2>{[['name','Nombre'],['username','Usuario'],['password','Contraseña (mín. 8)'],['province','Provincia'],['district','Partido / distrito'],['locality','Localidad (opcional)']].map(([k,l])=><label key={k} className="mt-4 block text-sm text-slate-300">{l}<input type={k==='password'?'password':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" required={['name','username','password'].includes(k)}/></label>)}<label className="mt-4 block text-sm">Rol<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="OPERATOR">Operador</option><option value="ADMIN">Administrador</option></select></label>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}<button className="mt-5 w-full rounded-xl bg-red-600 p-3 font-black">Crear usuario</button><p className="mt-3 text-xs text-slate-500">Si dejás localidad vacía, el permiso alcanza a todo el partido/distrito indicado.</p></form>
 <section className="space-y-3">{users.map(u=><article key={u.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-black">{u.name}</h3><span className="rounded-full bg-slate-800 px-2 py-1 text-xs">{u.role}</span><span className={u.active?'text-emerald-400':'text-red-400'}>{u.active?'● Activo':'● Suspendido'}</span></div><p className="text-sm text-slate-400">@{u.username}</p><div className="mt-2 text-sm text-slate-300">{u.zones.length?u.zones.map((z,i)=><div key={i}>📍 {z.locality?`${z.locality} · `:''}{z.district} · {z.province}</div>):<div>🌐 Sin zonas asignadas</div>}</div><p className="mt-2 text-xs text-slate-500">Último acceso: {u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('es-AR'):'Nunca'}</p></div><button onClick={()=>toggle(u)} className={`rounded-xl px-4 py-2 font-bold ${u.active?'bg-red-950 text-red-300':'bg-emerald-950 text-emerald-300'}`}>{u.active?'Suspender':'Activar'}</button></div></article>)}</section></div></div></main>;
}
